# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ffi-binary-libfixposix.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "mini_portile2", "~> 2.0"